Controllers/EmployeeController.cs
using EMS_Project.Models;
using EMS_Project.Repository.Employee;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System.Diagnostics;

namespace EMS_Project.Controllers
{
    
    public class EmployeeController : Controller
    {
        private readonly ILogger<EmployeeController> _logger;
        private readonly IEmployeeRepository _IemployeeRepository;
        private readonly IMemoryCache _memoryCache;
        private readonly string key = "EmployeeKey";

        //Injecting Services to controller
        public EmployeeController(ILogger<EmployeeController> logger,IEmployeeRepository employeeRepository,IMemoryCache memoryCache)
        {
            _logger = logger;
            _IemployeeRepository = employeeRepository;
            _memoryCache = memoryCache;
        }


        //Get Method for AddEmployee
        [HttpGet]
        public IActionResult AddEmployee()
        {
            return View();
        }


        //Post Method for AddEmployee
        [HttpPost]
        public async Task<IActionResult> AddEmployee([FromBody]Employee newEmp)
        {
            if (newEmp == null)
            {
                return BadRequest("Employee data cannot be null.");
            }

            try
            {
                await _IemployeeRepository.AddEmployee(newEmp);
                _logger.LogInformation("Employee added successfully: {@Employee}", newEmp);
                //return RedirectToAction("AddEmployee");
                return CreatedAtAction(nameof(AddEmployee), new { id = newEmp.EmployeeId }, newEmp);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error adding Employee");
                return StatusCode(StatusCodes.Status500InternalServerError, "An error occurred while adding the employee.");
            }
           // return View(newEmp);

        }


        //Get Method for EmployeeDetails
        [HttpGet]
        public async Task<IActionResult> EmployeeDetails()
        {
            // Data fetching message from cache or DB
            var stopwatch = new Stopwatch();
            stopwatch.Start();

            List<Employee> employees;

            if (_memoryCache.TryGetValue(key, out employees))
            {
                _logger.Log(LogLevel.Information, "Data fetched from cache");
            }
            else
            {
                _logger.Log(LogLevel.Information, "Data not fetched from cache");
                employees = await _IemployeeRepository.GetAllEmployees();

                var cacheEntryOptions = new MemoryCacheEntryOptions
                {
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(3600),
                    SlidingExpiration = TimeSpan.FromSeconds(45),
                    Priority = CacheItemPriority.Normal
                };

                _memoryCache.Set(key, employees, cacheEntryOptions);
            }

            stopwatch.Stop();
            _logger.Log(LogLevel.Information, "Time taken to fetch data: " + stopwatch.ElapsedMilliseconds);
            //    return View(Employees);


            // Return employees as JSON
            return Ok(employees);
        }


        //Cache Clear Method
        public IActionResult ClearCache()
        {
            _memoryCache.Remove(key);
            _logger.Log(LogLevel.Information, "Cleared cache");
            return RedirectToAction("EmployeeDetails");

        }
        //Get Method for DeleteEmployee using EmployeeId
        //[HttpGet]
        [HttpDelete]
        public async Task<IActionResult> DeleteEmployee(string id)
        {
            var result = await _IemployeeRepository.DeleteEmployee(id);
            if (result == false)
            {
                return NotFound();
            }
            //return RedirectToAction("EmployeeDetails");
            return Ok();
        }


        //Get Method for EditEmployee using EmployeeId to show the Employee details
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var Employee = await _IemployeeRepository.GetEmployeeById(id);

            if (Employee == null)
            {
                return NotFound();
            }
            //return View(Employee);
            return Ok(Employee);

        }


        //Post Method for EditEmployee to update the Employee details
        //[HttpPost]
        [HttpPut]
        public async Task<IActionResult> Edit([FromBody]Employee employee,string id)
        {
            var result = await _IemployeeRepository.UpdateEmployee(employee);
            //if (result)
            //{
            //    return RedirectToAction("EmployeeDetails");
            //}
            //return View(employee);
            return Ok();
        }


        //Calculate Work Days Get Method
        [HttpGet]
        public  IActionResult WorkDayCalculator()
        {
            return View();
        }

        //Calculate Work Days Post Method
        [HttpPost]
        public async Task<IActionResult> WorkDayCalculator(DateOnly StartDate,DateOnly EndDate)
        {
            var Days = await _IemployeeRepository.CalculateWorkDates(StartDate, EndDate);
            ViewBag.Days = Days;
            return View();
        }

    }
}

Controllers/HolidayController.cs
using EMS_Project.Models;
using EMS_Project.Repository.Holiday;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System.Diagnostics;
using System.Security.Claims;

namespace EMS_Project.Controllers
{
    //[Authorize]
    public class HolidayController : Controller
    {
   
        private readonly ILogger<HolidayController> _logger;
        private readonly IHolidayRepository _IholidayRepository;
        private readonly IMemoryCache _memoryCache;
        private readonly string key = "HolidayKey";

        //Injecting Services to controller
        public HolidayController(ILogger<HolidayController> logger, IHolidayRepository holidayRepository, IMemoryCache memoryCache)
        {
            _logger = logger;
            _IholidayRepository = holidayRepository;
            _memoryCache = memoryCache;
        }


        //Add Holiday Get Method
        
        [HttpGet]
        public IActionResult AddHoliday()
        {
            string Id = HttpContext.User.FindFirstValue("id");
            string Email = HttpContext.User.FindFirstValue(ClaimTypes.Email);
            string UserName = HttpContext.User.FindFirstValue(ClaimTypes.Name);
            return View();
        }


        //Add Holiday Post Method
        [HttpPost]
        public async Task<IActionResult> AddHoliday([FromBody]Holiday holiday)
        {

            try
            {
                await _IholidayRepository.AddHoliday(holiday);
                //return RedirectToAction("AddHoliday");
                return Ok();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error adding Holiday");
                return BadRequest(ex);
            }
           // return View(holiday);
           

        }


        //Get Method for All Holiday Details
        [HttpGet]
        public async Task<IActionResult> HolidayDetails()
        {
            //Data fetching message from cache or DB
            var stopwatch = new Stopwatch();
            stopwatch.Start();
            List<Holiday> Holidays;
            if (_memoryCache.TryGetValue(key, out Holidays))
            {
                _logger.Log(LogLevel.Information, "Data fetched from cache");
            }
            else
            {
                _logger.Log(LogLevel.Information, "Data not fetched from cache");
                Holidays = await _IholidayRepository.GetAllHolidays();
                var cacheEntryOptions = new MemoryCacheEntryOptions
                {
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(3600),
                    SlidingExpiration = TimeSpan.FromSeconds(45),
                    Priority = CacheItemPriority.Normal
                };
                _memoryCache.Set(key, Holidays, cacheEntryOptions);
            }
            stopwatch.Stop();
            _logger.Log(LogLevel.Information, "Time taken to fetch data: " + stopwatch.ElapsedMilliseconds);

            //return View(Holidays);
            return Ok(Holidays);
        }

        //Cache Clear Method
        public IActionResult ClearCache()
        {
            _memoryCache.Remove(key);
            _logger.Log(LogLevel.Information, "Cleared cache");
            return RedirectToAction("HolidayDetails");

        }

        //Delete Holiday by ID
        [HttpDelete]
        public async Task<IActionResult> DeleteHoliday(int id)
        {
            var result = await _IholidayRepository.DeleteHoliday(id);
            if (result == false)
            {
                return NotFound();
            }
            //return RedirectToAction("HolidayDetails");
            return Ok();
        }


        //Edit Holiday Get Method
        [HttpGet]
        public async Task<IActionResult> EditHoliday(int id)
        {
            var holiday = await _IholidayRepository.GetHolidayById(id);
            if (holiday == null)
            {
                return NotFound();
            }
            //return View(holiday);
            return Ok(holiday);
        }


        //Edit Holiday Post Method[HttpPost]

        [HttpPut]
        public async Task<IActionResult> EditHoliday([FromBody]Holiday holiday,int id)
        {
            try
            {
                await _IholidayRepository.UpdateHoliday(holiday);
                //return RedirectToAction("HolidayDetails");
                return Ok();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating Holiday");
                return BadRequest(ex);
            }
            //return View(holiday);
            
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMS_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EMS_Project.styles.css" asp-append-version="true" />
   
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EMS_Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee"asp-action="WorkDayCalculator">Calculate working days</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="AddEmployee">HR Options</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    

    
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EMS_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutActions.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Mangement System </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EMS_Project.styles.css" asp-append-version="true" />
   

</head>

@*--------------------------- This layout for the Employeers------------------------------------------------------------ *@
<body>
    <div class="MainContainer ">
        <div class="TitleContainer shadow bg-body-tertiary rounded  border border-2">
            <p class="fs-4 fw-bold"> Employee Options</p>
        </div>
        <div class="BodyDiv">
            <div class="OptionsContainer border  border-end border-3 border-start-0 ">

                <ul class="nav flex-column p-2 m-1 gap-3">

                    <li class="btn btn-outline-secondary text-secondary-emphasis">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Back To Home</a>
                    </li>

                    <li class="btn btn-outline-secondary text-secondary-emphasis">
                        <a class="nav-link" asp-controller="Employee" asp-action="WorkDayCalculator">Calculate Days</a>
                    </li>
                    <li class="btn btn-outline-secondary">
                        <a class="nav-link" asp-controller="Employee" asp-action="EmployeeDetails">Show Employees</a>
                    </li>
                    
                    
                </ul>
                
            </div>

            <div class="ContainerView row justify-content-center">

                <div class="card w-75 p-3 shadow-lg bg-body-tertiary rounded">
                    @RenderBody()
                </div>
                
                   
                
            </div>
        </div>

    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutOptions.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Mangement System </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EMS_Project.styles.css" asp-append-version="true" />
    
    
    

</head>
@*--------------------------- This layout for the HR------------------------------------------------------------ *@
<body>

    <div class="MainContainer ">

        <div class="TitleContainer shadow bg-body-tertiary rounded  border border-2">
            <p class="fs-4 fw-bold"> HR Options</p>
        </div>

        <div class="BodyDiv">

            <div class="OptionsContainer border border-end border-3 border-start-0 ">

                <ul class="nav flex-column p-2 m-1 gap-3">

                    <li class="btn btn-outline-secondary text-secondary-emphasis">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Back To Home</a>
                    </li>

                    <li class="nav-item dropdown btn btn-outline-secondary">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Employee Actions</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-action="AddEmployee" asp-controller="Employee">Add Employee</a></li>
                            <li><a class="dropdown-item" asp-controller="Employee" asp-action="EmployeeDetails">Show Employees</a></li>
                            
                            
                        </ul>
                    </li>

                    <li class="nav-item dropdown btn btn-outline-secondary">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Holiday Actions</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-action="AddHoliday" asp-controller="Holiday">Add Holiday</a></li>
                            <li><a class="dropdown-item" asp-action="HolidayDetails" asp-controller="Holiday">Show Holidays</a></li>

                        </ul>
                    </li>
                </ul>


            </div>

            <div class="ContainerView row justify-content-center">

                <div class="card w-75 p-3 shadow-lg bg-body-tertiary rounded">
                    @RenderBody()
                </div>

                


            </div>
        </div>

    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>